### ISSUE TITLE
Google Maps API Error: MissingKeyMapError

### ISSUE THREAD

**Issue by jakeparis** [performant-software/Neatline#398]
I'm getting this error ([described here](https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error)), even when I don't use a Google map as the base layer. 

I don't see anywhere within the Neatline Exhibit Settings to enter a Google Maps API key.

**Comment by kaitlinnewson** [comment]
Also having this issue, using Omeka 2.4.1 and Neatline 2.5.1.

This is the console log:

Failed to load resource: net::ERR_CONNECTION_REFUSED
(at http://localhost:35729/livereload.js)

Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
(at util.js:220)

Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
(at util.js:220)

Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
(at util.js:220)

Google Maps API error: Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
(at js?v=3.20&sensor=false:32)

**Comment by apjmason** [comment]
Giving this a bump since I encountered the same errors as @kaitlinnewson above.  When I try to turn on a Google map layer with the radio button I get this additional error message.

Uncaught TypeError: Cannot read property 'parentNode' of undefined(…)
- setGMapVisibility @ neatline-public.js:32
- display @ neatline-public.js:17
- setVisibility @ neatline-public.js:16
- setVisibility @ neatline-public.js:17
- setBaseLayer @ neatline-public.js:15
- onButtonClick @ neatline-public.js:37
- triggerEvent @ neatline-public.js:15
- buttonClick @ neatline-public.js:15
- triggerEvent @ neatline-public.js:15
- handleBrowserEvent @ neatline-public.js:15
- (anonymous function) @ neatline-public.js:13

I tried the version of neatline-public.js in pr #387 but that didn't work for me either.  

Is a fix in the works for this?  The Geolocation plugin of Omeka lets you [add an API key through the config form](https://forum.omeka.org/t/geolocation-requires-google-api-key/607/15).  Could this be added here?  Thanks!

**Comment by yigaler** [comment]
Still having this problem. Any fix for it?

**Comment by jamiefolsom** [comment]
Hi @jakeparis, @adarwinian, @kaitlinnewson and @yigaler, this is fixed in master, via #410, which allows for Neatline to be configured with an Google API key, per @apjmason's suggestion. The fix will be included in the next release, but if you'd like to try this out now, we'd welcome your feedback. Thanks!

**Comment by jgolight** [comment]
I'm still having this issue with the Google Maps API error message--I'm getting the I'm using Omeka 2.5 and Neatline 2.5.1. There's no button to configure Neatline in my installation. Has the fix been deployed yet? Thanks!

**Comment by jeremyboggs** [comment]
@jgolight This is fixed in the master branch. We'll wrap this up in a 2.5.2 release very soon.

**Comment by jamiefolsom** [comment]
Closed by #410.
