### ISSUE TITLE
Mysqli statement execute error:  Column 'added' cannot be null 

### ISSUE THREAD

**Issue by hklish01** [performant-software/Neatline#400]
I have Neatline installed. When I try to create a new exhibit I'm getting the following error message:

Zend_Db_Statement_Mysqli_Exception
Mysqli statement execute error : Column 'added' cannot be null

There was an older Omeka forum message related to this exact error but I'm not sure I understand how to fix it in my installation. http://omeka.org/forums-legacy/topic/neatline-error-11

Any help is appreciated.

exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' in ../omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:

0 ../omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
1 ../omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
2 ../omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(169): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
3 ../omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(110): Neatline_Row_Abstract->insertOrUpdate(Array)
4 ../omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
5 ../omeka/plugins/Neatline/models/NeatlineExhibit.php(58): Neatline_Row_Expandable->save()
6 ../omeka/plugins/Neatline/controllers/ExhibitsController.php(95): NeatlineExhibit->saveForm(Array)
7 ../omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->addAction()
8 ../omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
9 ../omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
10 ../omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
11 ../omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
12 ../omeka/application/libraries/Omeka/Application.php(79): Zend_Application->run()
13 ../omeka/admin/index.php(28): Omeka_Application->run()
14 {main}

**Comment by zerocrates** [comment]
Small typo: the URL of the old forum post is http://omeka.org/forums-legacy/topic/neatline-error-1

**Comment by akstuhl** [comment]
I'm working on a patch to address this error now. Including notes on the likely problem/solution here for reference.

From linked forum thread:
> I resolved the issue. As far as I could tell, the issue was the same MYSQL issue encountered by the author of [this](https://github.com/omeka/plugin-CsvImport/issues/60) post. The issue for me was in neatline, and not CSV import. I traced the issue to Neatline_Row_Abstract.php and was able to modify the same line in the code to (apparently) conform with MySQL 5.6.6.

From GitHub issue referenced in forum thread:
> MySQL 5.6.6 added variable 'explicit_defaults_for_timestamp' and it's set to ON on Amazon RDS by default. Since this policy should be mainstream in the future, you should set timestamp explicitly.

User added `$this->added = date("Y-m-d H:i:s", time());` to the file in question.

**Comment by jamiefolsom** [comment]
Hi @jeremyboggs -- it sounded from my conversation with @akstuhl about it this morning as though this one was going to take some more time -- OK if we push this one into the next release?

**Comment by jeremyboggs** [comment]
@jamiefolsom @akstuhl This was fixed in 2.6, right?

**Comment by jswafford** [comment]
I'm still encountering this error using both Omeka 2.6.1 and Omeka 2.4.1 with Neatline 2.6.1, and it's keeping me from saving Neatline records. It's the same stack trace:

2018-11-07T21:35:18+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' in /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
```
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(169): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(110): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineExhibit.php(58): Neatline_Row_Expandable->save()
#6 /usr/local/htdocs/omeka/plugins/Neatline/controllers/ExhibitsController.php(95): NeatlineExhibit->saveForm(Array)
#7 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->addAction()
#8 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#9 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954):errors.log
2018-11-07T21:35:18+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' in /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(169): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(110): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineExhibit.php(58): Neatline_Row_Expandable->save()
#6 /usr/local/htdocs/omeka/plugins/Neatline/controllers/ExhibitsController.php(95): NeatlineExhibit->saveForm(Array)
#7 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->addAction()
#8 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#9 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http:...skipping...
2018-11-07T21:35:18+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' in /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(169): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(110): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineExhibit.php(58): Neatline_Row_Expandable->save()
#6 /usr/local/htdocs/omeka/plugins/Neatline/controllers/ExhibitsController.php(95): NeatlineExhibit->saveForm(Array)
#7 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->addAction()
#8 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#9 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /usr/local/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /usr/local/htdocs/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /usr/local/htdocs/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#13 /usr/local/htdocs/omeka/admin/index.php(28): Omeka_Application->run()
#14 {main}
2018-11-08T16:32:01+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' in /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(171): Zend_Db_Adapter_Abstract-:...skipping...
2018-11-07T21:35:18+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'addd' cannot be null' in /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(169): Zend_Db_Adapter_Abstract->query('INSERT INTO `om..', Array)
#3 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(110): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineExhibit.php(58): Neatline_Row_Expandable->save()
#6 /usr/local/htdocs/omeka/plugins/Neatline/controllers/ExhibitsController.php(95): NeatlineExhibit->saveForm(Array)
#7 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->addAction()
#8 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#9 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Cntroller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /usr/local/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /usr/local/htdocs/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /usr/local/htdocs/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#13 /usr/local/htdocs/omeka/admin/index.php(28): Omeka_Application->run()
#14 {main}
2018-11-08T16:32:01+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'addd' cannot be null' in /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(171): Zend_Db_Adapter_Abstract->query('INSERT INTO `om..', Array)
#3 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(112): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineRecord.php(343): Neatline_Row_Expandable->save()
#6 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineRecord.php(163): NeatlineRecord->save()
#7 /usr/local/htdocs/omeka/plugins/Neatline/controllers/RecordsController.php(58): NeatlineRecord->saveForm(Array)
#8 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_RecordsController->postAction()
#9 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('postAction')
#10 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_ontroller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /usr/local/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#12 /usr/local/htdocs/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#13 /usr/local/htdocs/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
:...skipping...
2018-11-07T21:35:18+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be nul' in /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(169): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(110): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineExhibit.php(58): Neatline_Row_Expandable->save()
#6 /usr/local/htdocs/omeka/plugins/Neatline/controllers/ExhibitsController.php(95): NeatlineExhibit->saveForm(Array)
#7 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->addAction()
#8 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#9 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Reques_Http), Object(Zend_Controller_Response_Http))
#10 /usr/local/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /usr/local/htdocs/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /usr/local/htdocs/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#13 /usr/local/htdocs/omeka/admin/index.php(28): Omeka_Application->run()
#14 {main}
2018-11-08T16:32:01+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be nul' in /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(171): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(112): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineRecord.php(343): Neatline_Row_Expandable->save()
#6 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineRecord.php(163): NeatlineRecord->save()
#7 /usr/local/htdocs/omeka/plugins/Neatline/controllers/RecordsController.php(58): NeatlineRecord->saveForm(Array)
#8 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_RecordsController->postAction()
#9 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('postAction')
#10 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Requet_Http), Object(Zend_Controller_Response_Http))
#11 /usr/local/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#12 /usr/local/htdocs/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#13 /usr/local/htdocs/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#14 /usr/local/htdocs/omeka/index.php(23): Omeka_Application->run()
#15 {main}
2018-11-08T16:32:45+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be nu:
2018-11-07T21:35:18+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' i /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(169): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(110): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineExhibit.php(58): Neatline_Row_Expandable->save()
#6 /usr/local/htdocs/omeka/plugins/Neatline/controllers/ExhibitsController.php(95): NeatlineExhibit->saveForm(Array)
#7 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->addAction()
#8 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#9 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Htt), Object(Zend_Controller_Response_Http))
#10 /usr/local/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /usr/local/htdocs/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /usr/local/htdocs/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#13 /usr/local/htdocs/omeka/admin/index.php(28): Omeka_Application->run()
#14 {main}
2018-11-08T16:32:01+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' i /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(171): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(112): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineRecord.php(343): Neatline_Row_Expandable->save()
#6 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineRecord.php(163): NeatlineRecord->save()
#7 /usr/local/htdocs/omeka/plugins/Neatline/controllers/RecordsController.php(58): NeatlineRecord->saveForm(Array)
#8 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_RecordsController->postAction()
#9 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('postAction')
#10 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Htp), Object(Zend_Controller_Response_Http))
#11 /usr/local/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#12 /usr/local/htdocs/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#13 /usr/local/htdocs/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#14 /usr/local/htdocs/omeka/index.php(23): Omeka_Application->run()
#15 {main}
2018-11-08T16:32:45+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' i:
2018-11-07T21:35:18+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' in /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(169): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(110): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineExhibit.php(58): Neatline_Row_Expandable->save()
#6 /usr/local/htdocs/omeka/plugins/Neatline/controllers/ExhibitsController.php(95): NeatlineExhibit->saveForm(Array)
#7 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->addAction()
#8 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#9 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /usr/local/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /usr/local/htdocs/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /usr/local/htdocs/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#13 /usr/local/htdocs/omeka/admin/index.php(28): Omeka_Application->run()
#14 {main}
2018-11-08T16:32:01+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' in /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /usr/local/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(171): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(112): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /usr/local/htdocs/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineRecord.php(343): Neatline_Row_Expandable->save()
#6 /usr/local/htdocs/omeka/plugins/Neatline/models/NeatlineRecord.php(163): NeatlineRecord->save()
#7 /usr/local/htdocs/omeka/plugins/Neatline/controllers/RecordsController.php(58): NeatlineRecord->saveForm(Array)
#8 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_RecordsController->postAction()
#9 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('postAction')
#10 /usr/local/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /usr/local/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#12 /usr/local/htdocs/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#13 /usr/local/htdocs/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#14 /usr/local/htdocs/omeka/index.php(23): Omeka_Application->run()
#15 {main}
2018-11-08T16:32:45+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'added' cannot be null' in /userrors.log
```
Is there a way to fix this? I'm helping students make Neatline exhibits in a class next Wednesday, and we'll have to give them a new final assignment if we can't get this working.

**Comment by jamiefolsom** [comment]
Hi @jswafford, I will take a look at this. There was a patch in v2.6.0 that was supposed to fix this, but it sounds as though either that didn't do the trick, or this is a different issue. Are you seeing the problem upon new exhibit creation? Thanks.

**Comment by jswafford** [comment]
Thanks for taking a look! I'm seeing the problem any time I try to save a new record in Neatline, whether it's a new or old exhibit.

**Comment by jamiefolsom** [comment]
@jswafford ok, so that's potentially the same issue, but cropping up in a different place. Can you confirm that you're able to create and save new exhibits without an issue?

**Comment by jswafford** [comment]
@jamiefolsom Sorry for the confusion: I can create and save new Neatline exhibits without a problem; the problem just occurs when I try to create and save records in a Neatline exhibit.

**Comment by jamiefolsom** [comment]
Hi @jswafford -- no worries, just want to confirm. When you have a moment, would you also click the "System Information" link at bottom right of your Omeka admin dashboard, and let me know what you see in the "MySQL Server" line? Thanks!

**Comment by jswafford** [comment]
@jamiefolsom  Sure! It says "5.6.41"

**Comment by jamiefolsom** [comment]
Hi @jswafford, OK, I think that confirms my suspicion that this is the same issue we saw on the ExhibitRecord model. If you're feeling game, try applying this patch to `models/NeatlineRecord.php`.

```diff
diff --git a/models/NeatlineRecord.php b/models/NeatlineRecord.php
index 1a521c303..6030e7f5c 100644
--- a/models/NeatlineRecord.php
+++ b/models/NeatlineRecord.php
@@ -51,6 +51,13 @@ class NeatlineRecord extends Neatline_Row_Expandable
     public $map_zoom;
     public $map_focus;
 
+    protected function _initializeMixins()
+    {
+        parent::_initializeMixins();
+        $this->_mixins[] = new Mixin_Timestamp($this, 'added', null);
+    }

     /**
      * Required style attributes set in `styles.ini`.

```
I will also test and make a proper patch release, but I don't want to hold you up since you've got student projects in the queue.

**Comment by jswafford** [comment]
@jamiefolsom It works!!!! Thank you so much!!

**Comment by jamiefolsom** [comment]
@jswafford Great, thanks for testing it! I will make a patch release at some point soon.
